### ISSUE TITLE
Pre-built binaries requires libc 2.33 but only 2.31 found

### ISSUE THREAD

**Issue by terryfork** [eFiniLan/xnxpilot#1]
Binaries /data/openpilot/selfdrive/ui/_ui and /data/openpilot/selfdrive/ui/qt/spinner requires to run libc 2.33

./qt/spinner: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./qt/spinner)

./_ui: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./_ui)

But the latest version for ubuntu 18.04/Jetpack 4.6 is 2.31.

**Comment by eFiniLan** [comment]
Hi @terryfork ,
Thanks for that, I think I made a mistake with that (I was going to manually compile a lib that require higher glibc)
In the mean time, you can download the openpilot 0.8.9  ui source and compile from that.

I'll fix it up asap :)
