### ISSUE TITLE
issue about the camera

### ISSUE THREAD

**Issue by lucianzhong** [eFiniLan/xnxpilot#6]
Thanks for sharing this great work.

I do have an issue about the camera. I have a xaiver AGX instead of xavier NX which is not supported by  IMX477. Is there any cheap camera can be used by xavier AGX or  Is  usb-camera be possible to use?

**Comment by eFiniLan** [comment]
Hi @lucianzhong,
sorry for the late reply, with the implementation, there is no limitation on which camera you use, however, you will need to find the right parameters to calibrate it properly.

check out /selfdrive/camerad/cameras/camera_mipi.cc for more information.
